import type { Metadata } from "next";
import "./globals.css";
import "@/app/assets/css";

import ScriptsLoader from "./components/ScriptsLoader";
import ParticlesInit from "./components/layout/ParticlesInit";
import AjaxPortfolioPopup from "./components/ui/AjaxPortfolioPopup";
import Navside from "./components/layout/Navside";
import Preloader from "./components/ui/preloader";

const scripts = [
  "/js/modernizr.js",
  "/js/jquery.min.js",
  "/js/popper.min.js",
  "/js/bootstrap.min.js",
  "/js/macy.min.js",
  "/js/page-transition.min.js",
  "/js/jquery.animatedheadline.js",
  "/js/owl.carousel.min.js",
  "/js/fitty.min.js",
  "/js/isotope.pkgd.min.js",
  "/js/modulo-columns.js",
  "/js/jquery.magnific-popup.min.js",
  "/js/simplebar.min.js",
  "/js/tilt.jquery.min.js",
  "/js/jquery.vide.min.js",
  "/js/jquery.superslides.min.js",
  "/js/particles.min.js",
  "/js/jquery.mb.YTPlayer.min.js",
  "/js/main.js",
  "/js/main-demo.js",
];

export const metadata: Metadata = {
  title: "Eric's Resume CV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-random-animation="false" data-animation="19">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Monsieur+La+Doulaise&display=swap" rel="stylesheet" />
      </head>
      <body>
        <Preloader />

        <div id="page">
          <Navside />

          <div id="main" className="site-main">
            {children}
          </div>
        </div>

        <AjaxPortfolioPopup />
        <ParticlesInit />

        <ScriptsLoader scriptPaths={scripts} />
      </body>
    </html>
  );
}
